name: persistent_storage
description: A storage that saves the data in a device's persistent memory.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.2.0
  mocktail: ^0.1.0
